theme: jekyll-theme-midnight
title: erikrz
description: just another drop in the ocean
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]
github:
  is_project_page: false
  repository_url: https://github.com/erikrz